apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      containers:
        - name: conversaotemperatura
          image: fabricioveronez/conversao-temperatura:v1
---
apiVersion: v1
kind: Service
metadata: 
  name: api-temperatura-service
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
      type: nodePort
